let project = [
    // QTripStatic
    {
        name: "QTripStatic",
        mfr: "Jul 2023",
        link: "https://abuqamar-qtrip.netlify.app/",
        info: "QTrip is a travel website aimed at travellers looking for a multitude of adventures in different cities. ", // Durinf the course of this project
        modules: [
            "Created 3 different web pages from Wireframe layout using HTML and CSS",
            "Utilized Bootstrap extensively for responsive design",
            "Deployed the website to Netlify",
        ],
        skills: [
            "Bootstrap Display",
            "CSS positioning",
            "Bootstrap Responsive Images",
            "Bootstrap Flex",
            "Bootstrap Spacing",
            "HTML",
            "CSS",
            "Developer Tools",
            "Bootstrap",
            "CSS Flexbox",
            "Responsive Design",
            "VS Code Live Server",
            "Deployment",
            "Netlify",
            "Netlify CLI",
        ],
    },

    // QTripDynamic
    {
        name: "QTripDynamic",
        mfr: "Aug 2023",
        link: "https://abuqamar-qtrip-dynamic.netlify.app/",
        info: "QTrip is a travel website aimed at travellers looking for a multitude of adventures in different cities.", // During the course of this project
        modules: [
            "Created web pages using HTML and CSS and made them dynamic using JavaScript",
            "Improved UX with multi-select filters, image carousels",
            "Utilised localStorage to persist user preferences at client-side",
        ],
        skills: [
            "Netlify CLI",
            "Deployment",
            "Heroku",
            "Netlify",
            "Conditional Rendering",
            "Bootstrap Carousel",
            "Event Handling",
            "localStorage",
            "HTML",
            "CSS",
            "ES6",
            "JavaScript",
            "Developer Tools",
            "Bootstrap",
            "HTTP",
            "REST",
            "Responsive Design",
            "VS Code Live Server",
            "DOM Manipulation",
            "cURL",
            "JSON",
        ],
    },

    // XBoard
    {
        name: "XBoard",
        mfr: "Aug 2023",
        link: "https://abuqamar-xboard.netlify.app/",
        info: "XBoard is a News Feed website that will feature the latest news for select topics, from Flipboard.", // Durinf the course of this project
        modules: [
            "Built XBoard using HTML, CSS, Bootstrap and JavaScript from scratch",
            "Used Accordions and Image Carousel to improve UI",
            "Fetched news content from flipboard's RSS feed using REST API",
        ],
        skills: [
            "HTML",
            "CSS",
            "Figma",
            "Bootstrap",
            "ES6",
            "JavaScript",
            "DOM Manipulation",
            "Developer Tools",
            "REST",
            "JSON",
            "Netlify",
            "Netlify CLI",
            "Deployment",
            "VS Code Live Server",
            "Bootstrap Carousel",
        ],
    },

    // QKart Frontend
    {
        name: "QKart Frontend",
        mfr: "Sep 2023",
        link: "https://abuqamar-qkart.netlify.app/",
        info: "QKart is an e-commerce application offering a variety of products for customers to choose from. ", // During the course of this project
        modules: [
            "Implemented the core logic for authentication, shopping cart and checkout",
            "Improved UI by adding responsive design elements for uniform experience across different devices",
            "Utilized REST APIs to dynamically load and render data served by the backend server",
        ],
        skills: [
            "Deployement",
            "Netlify",
            "Material UI Grid",
            "Keyword Seacrh",
            "Debouncing",
            "LIFECYCLE METHODS",
            "React Router",
            "Material UI",
            "Responsive Design",
            "localStorage",
            "React Hooks",
            "Forms",
            "Controlled Components",
            "REST",
            "JSON",
            "Error Handling",
            "Developer Tools",
            "ES6",
            "Conditional Rendering",
            "React State & Props",
            "React",
            "Event Handling",
        ],
    },

    // Portfolio
    {
        name: "Portfolio",
        mfr: "Sep 2023",
        link: /*'https://abuqamar-portfolio.netlify.app/'*/ "#",
        info: "This is my portfolio.", // During the course of this project
        modules: [
            "Created web pages from scratch using HTML and CSS and made them dynamic using JavaScript",
            "Used accordion to improve UI",
            "Utilized Bootstrap extensively for responsive design",
            "Deployed the website to Netlify",
        ],
        skills: [
            "Bootstrap Display",
            "CSS Positioning",
            "Bootstrap Responsive Images",
            "Bootstrap Flex",
            "FlexBox",
            "Bootstrap Spacing",
            "HTML",
            "CSS",
            "JavaScript",
            "ES6",
            "Bootstrap",
            "CSS Flexbox",
            "Bootstrap Cards",
            "CSS Animation",
            "Dynamic Programming",
            "Responsive Design",
            "Conditional Rendering",
            "Event handling",
            "Developer Tools",
            "DOM Manipilation",
            "JSON objects",
            "VS Code Live Server",
            "GitHub Deployment",
            "Deployment",
            "Netlify",
            "Netlify CLI",
        ],
    },

    // GitHub Profile Searcher
    {
        name: "GitHub Profile Searcher",
        mfr: "Aug 2023",
        link: "https://abuqamar7379.github.io/GitHub-Profile-Searcher/",
        info: "A responsive web app that will query GitHub API to fetch user details based on username and show the details.", // Durinf the course of this project
        modules: [
            "Built Github Profile Searcher using HTML, CSS, Bootstrap and JavaScript from scratch",
            "Utilized Bootstrap extensively for responsive design",
            "Fetched profile content from github users api using REST API",
        ],
        skills: [
            "HTML",
            "CSS",
            "JavaScript",
            "Bootstrap",
            "HTTP",
            "JSON",
            "REST",
            "ES6",
            "DOM Manipulation",
            "Developer Tools",
            "Responsive Design",
            "VS Code Live Server",
            "GitHub Api",
            "Deployment",
            "GitHub Deployment",
        ],
    },

    // Weather App
    {
        name: "Weather App",
        mfr: "Sep 2023",
        link: "https://abuqamar7379.github.io/Weather-App/",
        info: "an Application that can give live details about the weather in any location.", // During the course of this project
        modules: [
            "Created web application from scratch using React",
            "Improved UI with the use of Material UI",
            "Fetched weather content from weather key api using REST API",
            "Deployed the website to Github Pages",
        ],
        skills: [
            "React",
            "JavaScript",
            "CSS",
            "HTML",
            "Material Design",
            "Functional Programming",
            "REST API",
            "Material UI",
            "Responsive Design",
            "ES6",
            "Event Handling",
            "Debouncing",
            "Mock API",
            "Conditional Rendering",
            "Dynamic Programming",
            "React State",
            "Controlled Components",
            "React Hooks",
            "Developer Tools",
            "Axios React",
            "Debouncing Functions",
            "VS Code Live Server",
            "GitHub Deployment",
            "React Effects",
            "Handling Side Effects",
            "Material UI Card",
        ],
    },
];

export { project };